# Generated by Django 2.1.4 on 2019-03-14 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketholders', '0002_noop_confirmed_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TShirtPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, help_text='Check this field to confirm this.')),
                ('size', models.CharField(choices=[('XS', 'Extra small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large'), ('XXL', 'Extra extra large'), ('XXXL', 'Larger than XXL')], default='medium', max_length=255)),
                ('fit', models.CharField(choices=[('fitted', 'fitted'), ('classic', 'classic')], default='medium', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
